name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: 'Run tests'
        run: npm run test.server